- hosts: 192.168.1.221
  become: yes
  become_user: root
  tasks:  
  
  - name: Install Git
    apt: 
      name: git
      state: present
      update_cache: yes
  - name: clonage
    git:
        repo: https://github.com/rahma-mejri/me-laravel.git
        dest: /laravel
